# Header
menu:
  主页: /
  所有文章: /archives
  生活: /tags/生活

# SubNav
subnav:
  github: "https://github.com/edisonator"
  weibo: "http://weibo.com/guancanghai"
  # rss: "#"
  zhihu: "https://www.zhihu.com/people/xu-hai-hao"
  #douban: "#"
  mail: "mailto://edisonator@gmail.com"
  facebook: "https://www.facebook.com/edisonator"
  google: "https://plus.google.com/u/0/117491710211438681601"
  twitter: "https://twitter.com/edisonator"
  linkedin: "https://www.linkedin.com/in/海浩-许-765325a6"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-52525871-2'
favicon: /favicon.png

#你的头像url
avatar: /images/edisonator.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
  # 奥巴马的博客: http://localhost:4000/
  # 卡卡的美丽传说: http://localhost:4000/
  # 本泽马的博客: http://localhost:4000/
  # 吉格斯的博客: http://localhost:4000/
  # 习大大大不同: http://localhost:4000/
  # 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 非典型性工科男，专注web前端开发，专注javascript。
